import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from "../_components/ui/navbar";


export const DefaultImage = "https://cdn.skims.com/images/hfqi0zm0/production/a9e758d3d4dfad734f35471cecc7d85f30d62f6c-706x894.jpg?q=95&auto=format"



export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // console.log(cookies().toString());

  return (
    <html lang="en">
      <TRPCReactProvider cookies={cookies().toString()}>
        <ClerkProvider>

          <body className={`font-sans`}>
            <Navbar />
            {children}
          </body>
        </ClerkProvider>
      </TRPCReactProvider>
    </html>
  );
}
